### PR TITLE
Enable Selinon backend

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Note I haven't tested this locally. I am gonna wait for CI to build an image and I will test it on dev cluster.

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msehnout** [comment]
Could you please add assertions for the "unused" imports, so that the CI is reporting correct results?

I don't think I can push into your personal repository.

**Comment by msrb** [comment]
> I don't think I can push into your personal repository.

This could be a separate PR. It's not like this PR introduced the problem with the imports :)

**Review by msehnout — APPROVED** [review]
LGTM

**Pull request merged**
